version: "3.8"

services:
  epub_voice_reader:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/proschu2/proschu2/epub_voice_reader
    volumes:
      - FOLDER_WITH_FILE_PATH:/app/data
    command: ["python", "/app/epub2tts_edge/epub2tts_edge.py"]
    environment:
      - NLTK_DATA=/app/epub2tts_edge/nltk_data
      - FILE=FILE
      - SPEAKER=en-US-AndrewMultilingualNeural
