services:
  epub_voice_reader:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/proschu2/proschu2/epub_voice_reader
    volumes:
      - FOLDER_WITH_FILE_PATH:/app/data
      - books:/app/tmp
    network_mode: "host"
    command: ["python", "/app/epub2tts_edge/epub2tts_edge.py"]
    environment:
      - FILE=FILE.epub
      - SPEAKER=en-US-AndrewMultilingualNeural
volumes:
  books:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "uid=1000,gid=1000,mode=1777"
